"""fk_ondelete_indexes_checks

Revision ID: 5e600f541933
Revises: e23499fdb0fc
Create Date: 2026-03-05 10:54:14.902556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e600f541933'
down_revision = 'e23499fdb0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('ix_document_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_document_uploaded_by_id', ['uploaded_by_id'], unique=False)
        batch_op.drop_constraint('document_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('document_uploaded_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['uploaded_by_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.drop_constraint('google_token_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('google_token_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_uploaded_by_id_fkey', 'user', ['uploaded_by_id'], ['id'])
        batch_op.create_foreign_key('document_category_id_fkey', 'category', ['category_id'], ['id'])
        batch_op.drop_index('ix_document_uploaded_by_id')
        batch_op.drop_index('ix_document_category_id')

    # ### end Alembic commands ###
