"""add due_date gc_event_id google_token

Revision ID: 6f085aacb300
Revises: 110a93fb41ca
Create Date: 2026-03-02 10:01:42.351848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f085aacb300'
down_revision = '110a93fb41ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_token_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gc_event_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('gc_event_id')
        batch_op.drop_column('due_date')

    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_token_user_id'))

    op.drop_table('google_token')
    # ### end Alembic commands ###
