"""add document indexes

Revision ID: 9bbe82e5b201
Revises: 5e600f541933
Create Date: 2026-03-09 12:01:19.041228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbe82e5b201'
down_revision = '5e600f541933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('ix_document_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('ix_document_created_at')

    # ### end Alembic commands ###
